export const crewTemplates = {
  rungun: {
    size: 'Run & Gun',
    crewSize: '5-15 crew',
    positions: [
      { position: 'Director', quantity: 1, department: 'Directing' },
      { position: 'Unit Production Manager', quantity: 1, department: 'Production' },
      { position: 'Production Assistant', quantity: 2, department: 'Production' },
      { position: 'Camera Operator', quantity: 1, department: 'Camera' },
      { position: 'Gaffer', quantity: 1, department: 'Electric' },
      { position: 'Sound Mixer', quantity: 1, department: 'Sound' },
      { position: 'Hair & Makeup Stylist', quantity: 1, department: 'Hair & Makeup' },
      { position: 'Editor', quantity: 1, department: 'Editorial' },
    ],
  },
  medium: {
    size: 'Medium',
    crewSize: '15-25 crew',
    positions: [
      { position: 'Director', quantity: 1, department: 'Directing' },
      { position: 'Unit Production Manager', quantity: 1, department: 'Production' },
      { position: 'Production Assistant', quantity: 4, department: 'Production' },
      { position: 'Camera Operator', quantity: 1, department: 'Camera' },
      { position: 'Gaffer', quantity: 1, department: 'Electric' },
      { position: 'Grip', quantity: 2, department: 'Grip' },
      { position: 'Sound Mixer', quantity: 1, department: 'Sound' },
      { position: 'Hair Stylist', quantity: 1, department: 'Hair' },
      { position: 'Makeup Artist', quantity: 1, department: 'Makeup' },
      { position: 'Wardrobe Stylist', quantity: 1, department: 'Costume / Wardrobe' },
      { position: 'Script Supervisor', quantity: 1, department: 'Script' },
      { position: 'Editor', quantity: 1, department: 'Editorial' },
      { position: 'Colorist', quantity: 1, department: 'Editorial' },
    ],
  },
  large: {
    size: 'Large',
    crewSize: '30-65 crew',
    positions: [
      { position: 'Director', quantity: 1, department: 'Directing' },
      { position: 'Producer', quantity: 1, department: 'Production' },
      { position: 'Unit Production Manager', quantity: 1, department: 'Production' },
      { position: 'Production Coordinator', quantity: 1, department: 'Production' },
      { position: '1st AD', quantity: 1, department: 'Directing' },
      { position: 'Production Accountant', quantity: 1, department: 'Accounting' },
      { position: 'Location Manager', quantity: 1, department: 'Locations' },
      { position: 'Casting Director', quantity: 1, department: 'Casting' },
      { position: 'Casting Assistant', quantity: 1, department: 'Casting' },
      { position: 'Director of Photography', quantity: 1, department: 'Camera' },
      { position: 'Camera Operator', quantity: 2, department: 'Camera' },
      { position: 'Gaffer', quantity: 1, department: 'Electric' },
      { position: 'Electric', quantity: 1, department: 'Electric' },
      { position: 'Key Grip', quantity: 1, department: 'Grip' },
      { position: 'Grip', quantity: 2, department: 'Grip' },
      { position: 'Sound Mixer', quantity: 1, department: 'Sound' },
      { position: 'Boom Operator', quantity: 2, department: 'Sound' },
      { position: 'Production Designer', quantity: 1, department: 'Art' },
      { position: 'Art Director', quantity: 1, department: 'Art' },
      { position: 'Set Decorator', quantity: 1, department: 'Art' },
      { position: 'Prop Master', quantity: 1, department: 'Property' },
      { position: 'Costume Designer', quantity: 1, department: 'Costume / Wardrobe' },
      { position: 'Hair Stylist', quantity: 1, department: 'Hair' },
      { position: 'Makeup Artist', quantity: 1, department: 'Makeup' },
      { position: 'Script Supervisor', quantity: 1, department: 'Script' },
      { position: 'Editor', quantity: 1, department: 'Editorial' },
      { position: 'Colorist', quantity: 1, department: 'Editorial' },
      { position: 'Craft Service', quantity: 1, department: 'Craft Services' },
      { position: 'Driver', quantity: 1, department: 'Transportation' },
    ],
  },
  full: {
    size: 'Full',
    crewSize: '70-120+ crew',
    positions: [],
  },
};
