name: DCP Spec Validation

on:
  push:
    branches: [ main, repo-reorganization ]
    paths:
      - 'packages/dcp-spec/**'
      - '.github/workflows/spec-validation.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages/dcp-spec/**'
      - '.github/workflows/spec-validation.yml'

jobs:
  validate-spec:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Validate JSON schemas
      run: npm run lint:spec
    
    - name: Check version bump (on PR)
      if: github.event_name == 'pull_request'
      run: |
        # Get the version from main branch
        git fetch origin main
        MAIN_VERSION=$(git show origin/main:packages/dcp-spec/package.json | grep '"version"' | cut -d'"' -f4)
        CURRENT_VERSION=$(grep '"version"' packages/dcp-spec/package.json | cut -d'"' -f4)
        
        if [ "$MAIN_VERSION" = "$CURRENT_VERSION" ]; then
          echo "❌ Version must be bumped when changing spec package"
          echo "Current version: $CURRENT_VERSION"
          echo "Please bump the version in packages/dcp-spec/package.json"
          exit 1
        else
          echo "✅ Version bumped from $MAIN_VERSION to $CURRENT_VERSION"
        fi
    
    - name: Validate package exports
      run: |
        cd packages/dcp-spec
        node -e "
          import('./index.js').then(pkg => {
            const requiredExports = [
              'componentSchema', 'configSchema', 'manifestSchema', 
              'themeSchema', 'openApiSpec', 'mcpManifest',
              'DCP_VERSION', 'DCP_SCHEMA_VERSION'
            ];
            
            const missing = requiredExports.filter(exp => !(exp in pkg));
            if (missing.length > 0) {
              console.error('❌ Missing exports:', missing);
              process.exit(1);
            }
            
            console.log('✅ All required exports are available');
          })
        "